package br.questor.teste.ebs.view;

import br.questor.teste.ebs.test.TesteConexao;
import br.questor.teste.ebs.control.DAO;

public class Conectar extends javax.swing.JFrame {

    private boolean statusEBS = false;
    private boolean statusQST = false;
    private String versao = "Versão 0.9.06 ©";
    
    public Conectar() {
        initComponents();
        btnIniciar.setEnabled(false);
        lblDireitosAutorais.setText(versao);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        prbCarregando = new javax.swing.JProgressBar();
        lblStatus = new javax.swing.JLabel();
        lblDireitosAutorais = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        pnlEBS = new javax.swing.JPanel();
        lblEnderecoEBS = new javax.swing.JLabel();
        txtEnderecoEBS = new javax.swing.JTextField();
        lblUsuarioEBS = new javax.swing.JLabel();
        txtUsuarioEBS = new javax.swing.JTextField();
        lblSenhaEBS = new javax.swing.JLabel();
        txtSenhaEBS = new javax.swing.JPasswordField();
        btnTestarEBS = new javax.swing.JButton();
        lblPortaEBS = new javax.swing.JLabel();
        txtPortaEBS = new javax.swing.JTextField();
        lblBancoEBS = new javax.swing.JLabel();
        txtBancoEBS = new javax.swing.JTextField();
        lblConexaoEBS = new javax.swing.JLabel();
        lblStatusEBS = new javax.swing.JLabel();
        pnlQST = new javax.swing.JPanel();
        lblEnderecoQST = new javax.swing.JLabel();
        txtEnderecoQST = new javax.swing.JTextField();
        lblUsuarioQST = new javax.swing.JLabel();
        txtUsuarioQST = new javax.swing.JTextField();
        lblSenhaQST = new javax.swing.JLabel();
        txtSenhaQST = new javax.swing.JPasswordField();
        btnTestarQST = new javax.swing.JButton();
        lblAliaseQST = new javax.swing.JLabel();
        txtAliaseQST = new javax.swing.JTextField();
        txtPortaQST = new javax.swing.JTextField();
        lblOuQST = new javax.swing.JLabel();
        lblPortaQST = new javax.swing.JLabel();
        lblConexaoQST = new javax.swing.JLabel();
        lblStatusQST = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnIniciar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EBS x Questor");
        setResizable(false);

        lblStatus.setText("Aguardando testes de conexão...");

        lblDireitosAutorais.setText("Versão x.x.xx ©");

        pnlEBS.setBorder(javax.swing.BorderFactory.createTitledBorder("EBS SQL Server"));

        lblEnderecoEBS.setText("Endereço:");

        txtEnderecoEBS.setText("127.0.0.1");
        txtEnderecoEBS.setToolTipText("Ex.: 192.168.0.140, localhost, 127.0.0.0");
        txtEnderecoEBS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtEnderecoEBSMouseEntered(evt);
            }
        });
        txtEnderecoEBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoEBSActionPerformed(evt);
            }
        });

        lblUsuarioEBS.setText("Usuário:");

        txtUsuarioEBS.setText("sa");
        txtUsuarioEBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioEBSActionPerformed(evt);
            }
        });

        lblSenhaEBS.setText("Senha:");

        txtSenhaEBS.setText("FGH567!");
        txtSenhaEBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaEBSActionPerformed(evt);
            }
        });

        btnTestarEBS.setText("Testar");
        btnTestarEBS.setToolTipText("Clique para testar a conexão");
        btnTestarEBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestarEBSActionPerformed(evt);
            }
        });

        lblPortaEBS.setText("Porta:");

        txtPortaEBS.setText("291");
        txtPortaEBS.setToolTipText("Ex.: 391, 3555, 8008");
        txtPortaEBS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPortaEBSMouseEntered(evt);
            }
        });
        txtPortaEBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortaEBSActionPerformed(evt);
            }
        });

        lblBancoEBS.setText("Nome Banco:");

        txtBancoEBS.setText("EBS_Cordilheira_10927_RTHController");
        txtBancoEBS.setToolTipText("Nome do banco dentro do SQL Server");
        txtBancoEBS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBancoEBSMouseEntered(evt);
            }
        });
        txtBancoEBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBancoEBSActionPerformed(evt);
            }
        });

        lblConexaoEBS.setText("Status da Conexão:");

        lblStatusEBS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatusEBS.setText("N/A");

        javax.swing.GroupLayout pnlEBSLayout = new javax.swing.GroupLayout(pnlEBS);
        pnlEBS.setLayout(pnlEBSLayout);
        pnlEBSLayout.setHorizontalGroup(
            pnlEBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEBSLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlEBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBancoEBS)
                    .addComponent(lblPortaEBS, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEnderecoEBS, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(pnlEBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPortaEBS)
                    .addComponent(txtEnderecoEBS)
                    .addComponent(txtBancoEBS))
                .addGap(18, 18, 18)
                .addGroup(pnlEBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlEBSLayout.createSequentialGroup()
                        .addGroup(pnlEBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUsuarioEBS)
                            .addComponent(lblSenhaEBS))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSenhaEBS, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtUsuarioEBS))
                        .addGap(35, 35, 35))
                    .addGroup(pnlEBSLayout.createSequentialGroup()
                        .addComponent(lblConexaoEBS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatusEBS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEBSLayout.createSequentialGroup()
                .addGap(435, 435, 435)
                .addComponent(btnTestarEBS, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        pnlEBSLayout.setVerticalGroup(
            pnlEBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEBSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblUsuarioEBS)
                        .addComponent(txtUsuarioEBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEnderecoEBS)
                        .addComponent(txtEnderecoEBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSenhaEBS)
                        .addComponent(txtSenhaEBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPortaEBS)
                        .addComponent(txtPortaEBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBancoEBS)
                    .addComponent(txtBancoEBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConexaoEBS)
                    .addComponent(lblStatusEBS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTestarEBS)
                .addContainerGap())
        );

        pnlQST.setBorder(javax.swing.BorderFactory.createTitledBorder("Questor Firebird"));

        lblEnderecoQST.setText("Endereço:");

        txtEnderecoQST.setText("C:\\nQuestorAtt\\Base\\Questor_100.fdb");
        txtEnderecoQST.setToolTipText("Ex.: servidor\\banco.fdb, C:\\base\\questor.fdb");
        txtEnderecoQST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtEnderecoQSTMouseEntered(evt);
            }
        });
        txtEnderecoQST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoQSTActionPerformed(evt);
            }
        });

        lblUsuarioQST.setText("Usuário:");

        txtUsuarioQST.setText("sysdba");
        txtUsuarioQST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioQSTActionPerformed(evt);
            }
        });

        lblSenhaQST.setText("Senha:");

        txtSenhaQST.setText("masterkey");
        txtSenhaQST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaQSTActionPerformed(evt);
            }
        });

        btnTestarQST.setText("Testar");
        btnTestarQST.setToolTipText("Clique para testar a conexão");
        btnTestarQST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestarQSTActionPerformed(evt);
            }
        });

        lblAliaseQST.setText("Aliase:");

        txtAliaseQST.setToolTipText("Aliase criado na pasta do Firebird");
        txtAliaseQST.setEnabled(false);
        txtAliaseQST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAliaseQSTMouseEntered(evt);
            }
        });
        txtAliaseQST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAliaseQSTActionPerformed(evt);
            }
        });

        txtPortaQST.setText("3050");
        txtPortaQST.setToolTipText("Ex.: 3050, 3555, 8008");
        txtPortaQST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPortaQSTMouseEntered(evt);
            }
        });
        txtPortaQST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortaQSTActionPerformed(evt);
            }
        });

        lblOuQST.setText("ou");

        lblPortaQST.setText("Porta:");

        lblConexaoQST.setText("Status da Conexão:");

        lblStatusQST.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatusQST.setText("N/A");

        javax.swing.GroupLayout pnlQSTLayout = new javax.swing.GroupLayout(pnlQST);
        pnlQST.setLayout(pnlQSTLayout);
        pnlQSTLayout.setHorizontalGroup(
            pnlQSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQSTLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pnlQSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAliaseQST)
                    .addComponent(lblEnderecoQST)
                    .addComponent(lblPortaQST)
                    .addComponent(lblOuQST))
                .addGap(18, 18, 18)
                .addGroup(pnlQSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAliaseQST)
                    .addComponent(txtEnderecoQST, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(txtPortaQST))
                .addGap(18, 18, 18)
                .addGroup(pnlQSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlQSTLayout.createSequentialGroup()
                        .addGroup(pnlQSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUsuarioQST)
                            .addComponent(lblSenhaQST))
                        .addGap(18, 18, 18)
                        .addGroup(pnlQSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSenhaQST, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtUsuarioQST))
                        .addGap(35, 35, 35))
                    .addGroup(pnlQSTLayout.createSequentialGroup()
                        .addComponent(lblConexaoQST)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatusQST, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQSTLayout.createSequentialGroup()
                .addGap(435, 435, 435)
                .addComponent(btnTestarQST, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        pnlQSTLayout.setVerticalGroup(
            pnlQSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQSTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlQSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnderecoQST)
                    .addComponent(txtEnderecoQST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioQST)
                    .addComponent(txtUsuarioQST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlQSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaQST)
                    .addComponent(txtSenhaQST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOuQST))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlQSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAliaseQST)
                    .addComponent(txtAliaseQST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlQSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPortaQST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPortaQST)
                    .addComponent(lblConexaoQST)
                    .addComponent(lblStatusQST))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTestarQST)
                .addContainerGap())
        );

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));

        jLabel1.setText("● Execute os testes de conexão antes de prosseguir com o conversor.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnIniciar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEBS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlQST, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlQST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Conexão", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDireitosAutorais))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prbCarregando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prbCarregando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(lblDireitosAutorais))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEnderecoEBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoEBSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoEBSActionPerformed

    private void txtEnderecoEBSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEnderecoEBSMouseEntered
        
    }//GEN-LAST:event_txtEnderecoEBSMouseEntered

    private void btnTestarEBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestarEBSActionPerformed
        DAO.setEnderecoSQL(txtEnderecoEBS.getText());
        DAO.setPortaSQL(txtPortaEBS.getText());
        DAO.setNomeSQL(txtBancoEBS.getText());
        DAO.setUsernameSQL(txtUsuarioEBS.getText());
        
        String PasswordSQL = "" ;
        PasswordSQL = new String(txtSenhaEBS.getPassword());
        DAO.setPasswordSQL(PasswordSQL);
        
        try{
            TesteConexao testeconexao = new TesteConexao();
            testeconexao.testeEBS();
            lblStatusEBS.setText("Ok!");
            lblStatusEBS.setForeground(new java.awt.Color(0, 120, 0));
            statusEBS = true;
            if((statusEBS == true)&&(statusQST == true)){
                prbCarregando.setValue(100);
                lblStatus.setText("Pronto para ser iniciado.");
                btnIniciar.setEnabled(true);
            }
        }catch(Exception ex){
            lblStatusEBS.setText("Erro!");
            lblStatusEBS.setForeground(new java.awt.Color(120, 0, 0));
            statusEBS = false;
            lblStatus.setText("Aguardando testes de conexão...");
            btnIniciar.setEnabled(false);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnTestarEBSActionPerformed

    private void txtUsuarioEBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioEBSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioEBSActionPerformed

    private void txtSenhaEBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaEBSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaEBSActionPerformed

    private void txtBancoEBSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBancoEBSMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBancoEBSMouseEntered

    private void txtBancoEBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBancoEBSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBancoEBSActionPerformed

    private void txtEnderecoQSTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEnderecoQSTMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoQSTMouseEntered

    private void txtEnderecoQSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoQSTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoQSTActionPerformed

    private void txtUsuarioQSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioQSTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioQSTActionPerformed

    private void txtSenhaQSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaQSTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaQSTActionPerformed

    private void btnTestarQSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestarQSTActionPerformed
        DAO.setEnderecoQST(txtEnderecoQST.getText());
        DAO.setPortaQST(txtPortaQST.getText());
        DAO.setUsernameQST(txtUsuarioQST.getText());
        
        String PasswordQST = "" ;
        PasswordQST = new String(txtSenhaQST.getPassword());
        DAO.setPasswordQST(PasswordQST);
        
        try{
            TesteConexao testeconexao = new TesteConexao();
            testeconexao.testeQST();
            lblStatusQST.setText("Ok!");
            lblStatusQST.setForeground(new java.awt.Color(0, 120, 0));
            statusQST = true;
            if((statusEBS == true)&&(statusQST == true)){
                prbCarregando.setValue(100);
                lblStatus.setText("Pronto para ser iniciado.");
                btnIniciar.setEnabled(true);
            }
        }catch(Exception ex){
            lblStatusQST.setText("Erro!");
            lblStatusQST.setForeground(new java.awt.Color(120, 0, 0));
            statusQST = false;
            lblStatus.setText("Aguardando testes de conexão...");
            btnIniciar.setEnabled(false);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnTestarQSTActionPerformed

    private void txtAliaseQSTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAliaseQSTMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAliaseQSTMouseEntered

    private void txtAliaseQSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAliaseQSTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAliaseQSTActionPerformed

    private void txtPortaQSTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPortaQSTMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortaQSTMouseEntered

    private void txtPortaQSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortaQSTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortaQSTActionPerformed

    private void txtPortaEBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortaEBSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortaEBSActionPerformed

    private void txtPortaEBSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPortaEBSMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortaEBSMouseEntered

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        this.setVisible(false);
        new Principal().setVisible(true);
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conectar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conectar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conectar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conectar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conectar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnTestarEBS;
    private javax.swing.JButton btnTestarQST;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAliaseQST;
    private javax.swing.JLabel lblBancoEBS;
    private javax.swing.JLabel lblConexaoEBS;
    private javax.swing.JLabel lblConexaoQST;
    private javax.swing.JLabel lblDireitosAutorais;
    private javax.swing.JLabel lblEnderecoEBS;
    private javax.swing.JLabel lblEnderecoQST;
    private javax.swing.JLabel lblOuQST;
    private javax.swing.JLabel lblPortaEBS;
    private javax.swing.JLabel lblPortaQST;
    private javax.swing.JLabel lblSenhaEBS;
    private javax.swing.JLabel lblSenhaQST;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatusEBS;
    private javax.swing.JLabel lblStatusQST;
    private javax.swing.JLabel lblUsuarioEBS;
    private javax.swing.JLabel lblUsuarioQST;
    private javax.swing.JPanel pnlEBS;
    private javax.swing.JPanel pnlQST;
    private javax.swing.JProgressBar prbCarregando;
    private javax.swing.JTextField txtAliaseQST;
    private javax.swing.JTextField txtBancoEBS;
    private javax.swing.JTextField txtEnderecoEBS;
    private javax.swing.JTextField txtEnderecoQST;
    private javax.swing.JTextField txtPortaEBS;
    private javax.swing.JTextField txtPortaQST;
    private javax.swing.JPasswordField txtSenhaEBS;
    private javax.swing.JPasswordField txtSenhaQST;
    private javax.swing.JTextField txtUsuarioEBS;
    private javax.swing.JTextField txtUsuarioQST;
    // End of variables declaration//GEN-END:variables
}
